// Generated by dts-bundle-generator v9.5.1

import { InputMode } from 'lyrics-typing-engine';
import React$1 from 'react';
import z from 'zod';

export type RawPPInput = {
	accuracy: number;
	clearRate: number;
	minPlaySpeed: number;
};
declare function calcRawPP(result: RawPPInput, rating: number): number;
declare const CreateTypingResultJsonSchema: z.ZodArray<z.ZodObject<{
	status: z.ZodObject<{
		point: z.ZodOptional<z.ZodNumber>;
		timeBonus: z.ZodOptional<z.ZodNumber>;
		typeCount: z.ZodOptional<z.ZodNumber>;
		missCount: z.ZodOptional<z.ZodNumber>;
		lostCount: z.ZodOptional<z.ZodNumber>;
		rkpm: z.ZodOptional<z.ZodUnion<[
			z.ZodNumber,
			z.ZodLiteral<number>
		]>>;
		kpm: z.ZodOptional<z.ZodNumber>;
		typedHiragana: z.ZodOptional<z.ZodNullable<z.ZodString>>;
		lostHiragana: z.ZodOptional<z.ZodNullable<z.ZodString>>;
		lostWord: z.ZodOptional<z.ZodNullable<z.ZodString>>;
		combo: z.ZodNumber;
		typingTime: z.ZodNumber;
		mode: z.ZodEnum<{
			roma: "roma";
			kana: "kana";
			flick: "flick";
		}>;
		speed: z.ZodNumber;
	}, z.core.$strip>;
	types: z.ZodArray<z.ZodObject<{
		isCorrect: z.ZodOptional<z.ZodBoolean>;
		char: z.ZodOptional<z.ZodString>;
		option: z.ZodOptional<z.ZodEnum<{
			roma: "roma";
			kana: "kana";
			speedChange: "speedChange";
		}>>;
		time: z.ZodNumber;
	}, z.core.$strip>>;
}, z.core.$strip>>;
export type TypingLineResult = z.output<typeof CreateTypingResultJsonSchema>[number];
export type TypeResult = TypingLineResult["types"][number];
export type PlayingSceneType = "play" | "replay" | "practice";
export type EndSceneType = "play_end" | "practice_end" | "replay_end";
export type SceneType = "ready" | PlayingSceneType | EndSceneType;
declare const LineOptionSchema: z.ZodObject<{
	changeCSS: z.ZodOptional<z.ZodString>;
	eternalCSS: z.ZodOptional<z.ZodString>;
	isChangeCSS: z.ZodOptional<z.ZodBoolean>;
	changeVideoSpeed: z.ZodOptional<z.ZodNumber>;
	isCaseSensitive: z.ZodOptional<z.ZodBoolean>;
}, z.core.$strip>;
export interface TypeSuccessDetail {
	/** 入力したキー */
	successKey: string;
	/** チャンクが完了したか */
	isCompleted: boolean;
	/** チャンクの種別 */
	chunkType: string | undefined;
	/** ライン経過時間 (ms) */
	constantLineTime: number;
	/** この入力で加算された点数（`CHAR_POINT` 比で打鍵量の目安に使える） */
	updatePoint: number;
}
export interface TypeMissDetail {
	/** ミスしたキー */
	failKey: string;
}
export interface LineCompletedDetail {
	/** ライン経過時間 (ms) */
	constantLineTime: number;
}
export interface TimerUpdateDetail {
	/** 動画の現在時刻 (s) */
	currentTime: number;
	/** 動画の現在時刻（定数・補間なし）(s) */
	constantTime: number;
	/** ライン経過時間 (ms) */
	constantLineTime: number;
	/** ライン残り時間 (ms) */
	constantRemainLineTime: number;
}
export interface LineChangeDetail {
	/** 新しいラインのインデックス */
	nextCount: number;
}
export interface GameEndDetail {
	/** ゲーム終了時のライン経過時間 (ms) */
	constantLineTime: number;
}
export interface GameStartDetail {
	/** 開始シーン ("play" | "practice" | "replay") */
	scene: string;
}
export type PlayDetail = Record<never, never>;
export type PauseDetail = Record<never, never>;
export type ReadyDetail = Record<never, never>;
export interface RateChangeDetail {
	/** 変更後の再生速度 */
	speed: number;
}
export interface StateChangeDetail {
	/** YT.PlayerState の値 (-1 | 0 | 1 | 2 | 3 | 5) */
	state: number;
}
export interface SeekedDetail {
	/** シーク後の現在時刻（秒） */
	time: number;
}
export interface TickDetail {
	/** 動画の現在時刻 (s) */
	currentTime: number;
	/** ライン経過時間 (ms) */
	constantLineTime: number;
	/** ライン残り時間 (ms) */
	constantRemainLineTime: number;
}
export interface Timer1sUpdateDetail {
	/** 動画の現在時刻（定数・補間なし）(s) */
	constantTime: number;
}
export interface ChangeInputModeDetail {
	newInputMode: InputMode;
}
export type TypeEventMap = {
	"type:success": TypeSuccessDetail;
	"type:miss": TypeMissDetail;
	"type:lineCompleted": LineCompletedDetail;
	"replay:success": TypeSuccessDetail;
	"replay:miss": TypeMissDetail;
	"replay:lineCompleted": LineCompletedDetail;
	restart: null;
	"timer:tick": TickDetail;
	"timer:100msUpdate": TimerUpdateDetail;
	"timer:1sUpdate": Timer1sUpdateDetail;
	"timer:lineChange": LineChangeDetail;
	"timer:end": GameEndDetail;
	"yt:start": GameStartDetail;
	"yt:play": PlayDetail;
	"yt:pause": PauseDetail;
	"yt:ready": ReadyDetail;
	"yt:rateChange": RateChangeDetail;
	"yt:stateChange": StateChangeDetail;
	"yt:seeked": SeekedDetail;
	"change-input-mode": ChangeInputModeDetail;
};
export type TypeEventType = keyof TypeEventMap;
export type TypeEventCallback<T extends TypeEventType> = (detail: TypeEventMap[T]) => void;
declare const ytypingType: {
	readonly CHAR_POINT: number;
	readonly MISS_PENALTY_POINT: number;
	readonly getStatus: () => {
		score: number;
		type: number;
		kpm: number;
		rank: number;
		point: number;
		miss: number;
		lost: number;
		line: number;
		timeBonus: number;
	};
	readonly getSubstatus: () => {
		romaType: number;
		kanaType: number;
		flickType: number;
		englishType: number;
		spaceType: number;
		symbolType: number;
		numType: number;
		clearRate: number;
		kanaToRomaConvertCount: number;
		maxCombo: number;
		missCombo: number;
		totalTypeTime: number;
		completeCount: number;
		failureCount: number;
	};
	readonly getLineSubstatus: () => {
		typeCount: number;
		missCount: number;
		types: TypeResult[];
		startSpeed: number;
		startInputMode: InputMode;
	};
	readonly getTypingStats: () => {
		romaType: number;
		kanaType: number;
		flickType: number;
		englishType: number;
		spaceType: number;
		symbolType: number;
		numType: number;
		typingTime: number;
		maxCombo: number;
	};
	readonly getTypingWord: () => import("lyrics-typing-engine", { with: { "resolution-mode": "import" } }).TypingWord;
	readonly getInputMode: () => InputMode;
	readonly getLineResults: () => TypingLineResult[];
	readonly getSelectLineIndex: () => number;
	readonly getReplayRankingResult: () => {
		id: number;
		updatedAt: Date;
		rank: number;
		score: number;
		player: {
			id: number;
			name: string | null;
		};
		typeCounts: {
			romaType: number;
			kanaType: number;
			flickType: number;
			englishType: number;
			symbolType: number;
			spaceType: number;
			numType: number;
		};
		otherStatus: {
			playSpeed: number;
			miss: number;
			lost: number;
			maxCombo: number;
			clearRate: number;
			isCaseSensitive: boolean;
			pp: number;
		};
		typeSpeed: {
			kpm: number;
			rkpm: number;
			kanaToRomaKpm: number;
			kanaToRomaRkpm: number;
		};
		clap: {
			count: number;
			hasClapped: boolean;
		};
	} | null;
	readonly getScene: () => SceneType;
	readonly getBuiltMap: () => {
		lines: import("lyrics-typing-engine", { with: { "resolution-mode": "import" } }).BuiltMapLine<import("zod").infer<typeof LineOptionSchema>>[];
		totalNotes: {
			roma: number;
			kana: number;
		};
		keyRate: number;
		missRate: number;
		initialLineResults: TypingLineResult[];
		typingLineIndexes: number[];
		changeCSSIndexes: number[];
		duration: number;
		hasAlphabet: boolean;
		isCaseSensitive: boolean;
	} | null;
	readonly getTimeOffset: () => number;
	readonly getLineCount: () => number;
	readonly getYTPlayer: () => import("youtube").Player | null;
	readonly getYTPlayerState: () => import("youtube").PlayerState | undefined;
	readonly getYTVideoId: () => string | undefined;
	readonly getYTCurrentTime: () => number | undefined;
	readonly getMapInfo: () => {
		id: number;
		media: {
			previewTime: number;
			thumbnailQuality: "mqdefault" | "maxresdefault";
			videoId: string;
		};
		info: {
			tags: string[];
			title: string;
			artistName: string;
			source: string;
			duration: number;
			visibility: "PUBLIC" | "UNLISTED";
		};
		creator: {
			id: number;
			name: string | null;
			comment: string;
		};
		difficulty: {
			romaKpmMedian: number;
			kanaKpmMedian: number;
			romaKpmMax: number;
			kanaKpmMax: number;
			romaTotalNotes: number;
			kanaTotalNotes: number;
			rating: number;
		};
		like: {
			hasLiked: boolean;
		};
		bookmark: {
			hasBookmarked: boolean;
		};
		createdAt: Date;
		updatedAt: Date;
	} | undefined;
	readonly calcRawPP: typeof calcRawPP;
	readonly getUserTopPPs: () => Promise<{
		mapId: number;
		pp: number;
	}[]>;
	addEventListener<T extends TypeEventType>(type: T, callback: TypeEventCallback<T>): void;
	removeEventListener<T extends TypeEventType>(type: T, callback: TypeEventCallback<T>): void;
};
declare global {
	interface Window {
		__ytyping_type: typeof ytypingType;
	}
}
export type YTypingTypeAPI = typeof ytypingType;
export type ImeEventMap = {
	start: undefined;
	end: undefined;
};
export type ImeEventType = keyof ImeEventMap;
export type ImeEventCallback<T extends ImeEventType> = (detail: ImeEventMap[T]) => void;
declare const ytypingIme: {
	readonly ensureMapInfo: () => Promise<{
		id: number;
		media: {
			previewTime: number;
			thumbnailQuality: "mqdefault" | "maxresdefault";
			videoId: string;
		};
		info: {
			tags: string[];
			title: string;
			artistName: string;
			source: string;
			duration: number;
			visibility: "PUBLIC" | "UNLISTED";
		};
		creator: {
			id: number;
			name: string | null;
			comment: string;
		};
		difficulty: {
			romaKpmMedian: number;
			kanaKpmMedian: number;
			romaKpmMax: number;
			kanaKpmMax: number;
			romaTotalNotes: number;
			kanaTotalNotes: number;
			rating: number;
		};
		like: {
			hasLiked: boolean;
		};
		bookmark: {
			hasBookmarked: boolean;
		};
		createdAt: Date;
		updatedAt: Date;
	} | null>;
	readonly getBuiltMap: () => {
		lines: import("lyrics-ime-typing-engine", { with: { "resolution-mode": "import" } }).BuiltImeLine[];
		words: string[][][][];
		totalNotes: number;
		initWordResults: import("lyrics-ime-typing-engine", { with: { "resolution-mode": "import" } }).WordResult[];
		flatWords: string[];
	} | null;
	readonly getUserResults: () => {
		userId: string;
		name: string;
		typeCount: number;
		wordResults: import("lyrics-ime-typing-engine", { with: { "resolution-mode": "import" } }).WordResult[];
		currentWordIndex: number;
	}[];
	readonly getUserResult: (id: string) => import("lyrics-ime-typing-engine", { with: { "resolution-mode": "import" } }).UserResult | undefined;
	readonly updateUserResult: (id: string, { name, typeCountDelta, newWordResults, nextWordIndex, }: {
		name: string;
		typeCountDelta: number;
		newWordResults: import("lyrics-ime-typing-engine", { with: { "resolution-mode": "import" } }).WordResult[];
		nextWordIndex: number;
	}) => void;
	readonly updateUserName: (id: string, name: string) => void;
	readonly handleImeInput: ({ value, currentWordIndex, wordResults: _wordResults, }: {
		value: string;
		currentWordIndex: number | undefined;
		wordResults: import("lyrics-ime-typing-engine", { with: { "resolution-mode": "import" } }).WordResult[] | undefined;
	}) => {
		newWordResults: import("lyrics-ime-typing-engine", { with: { "resolution-mode": "import" } }).WordResult[];
		typeCountDelta: number;
		typeCountStatsDelta: number;
		nextWordIndex: number;
		appendNotifications: string[];
	};
	readonly addNotifications: (notifications: string[]) => void;
	addEventListener<T extends ImeEventType>(type: T, callback: ImeEventCallback<T>): void;
	removeEventListener<T extends ImeEventType>(type: T, callback: ImeEventCallback<T>): void;
};
declare global {
	interface Window {
		__ytyping_ime: typeof ytypingIme;
	}
}
export type YTypingImeAPI = typeof ytypingIme;
export type ToastTypes = "normal" | "action" | "success" | "info" | "warning" | "error" | "loading" | "default";
export type PromiseT<Data = any> = Promise<Data> | (() => Promise<Data>);
export interface PromiseIExtendedResult extends ExternalToast {
	message: React$1.ReactNode;
}
export type PromiseTExtendedResult<Data = any> = PromiseIExtendedResult | ((data: Data) => PromiseIExtendedResult | Promise<PromiseIExtendedResult>);
export type PromiseTResult<Data = any> = string | React$1.ReactNode | ((data: Data) => React$1.ReactNode | string | Promise<React$1.ReactNode | string>);
export type PromiseExternalToast = Omit<ExternalToast, "description">;
export type PromiseData<ToastData = any> = PromiseExternalToast & {
	loading?: string | React$1.ReactNode;
	success?: PromiseTResult<ToastData> | PromiseTExtendedResult<ToastData>;
	error?: PromiseTResult | PromiseTExtendedResult;
	description?: PromiseTResult;
	finally?: () => void | Promise<void>;
};
export interface ToastClassnames {
	toast?: string;
	title?: string;
	description?: string;
	loader?: string;
	closeButton?: string;
	cancelButton?: string;
	actionButton?: string;
	success?: string;
	error?: string;
	info?: string;
	warning?: string;
	loading?: string;
	default?: string;
	content?: string;
	icon?: string;
}
export interface Action {
	label: React$1.ReactNode;
	onClick: (event: React$1.MouseEvent<HTMLButtonElement, MouseEvent>) => void;
	actionButtonStyle?: React$1.CSSProperties;
}
export interface ToastT {
	id: number | string;
	toasterId?: string;
	title?: (() => React$1.ReactNode) | React$1.ReactNode;
	type?: ToastTypes;
	icon?: React$1.ReactNode;
	jsx?: React$1.ReactNode;
	richColors?: boolean;
	invert?: boolean;
	closeButton?: boolean;
	dismissible?: boolean;
	description?: (() => React$1.ReactNode) | React$1.ReactNode;
	duration?: number;
	delete?: boolean;
	action?: Action | React$1.ReactNode;
	cancel?: Action | React$1.ReactNode;
	onDismiss?: (toast: ToastT) => void;
	onAutoClose?: (toast: ToastT) => void;
	promise?: PromiseT;
	cancelButtonStyle?: React$1.CSSProperties;
	actionButtonStyle?: React$1.CSSProperties;
	style?: React$1.CSSProperties;
	unstyled?: boolean;
	className?: string;
	classNames?: ToastClassnames;
	descriptionClassName?: string;
	position?: Position;
	testId?: string;
}
export type Position = "top-left" | "top-right" | "bottom-left" | "bottom-right" | "top-center" | "bottom-center";
export interface ToastToDismiss {
	id: number | string;
	dismiss: boolean;
}
export type ExternalToast = Omit<ToastT, "id" | "type" | "title" | "jsx" | "delete" | "promise"> & {
	id?: number | string;
	toasterId?: string;
};
export type titleT = (() => React$1.ReactNode) | React$1.ReactNode;
declare const toast: ((message: titleT, data?: ExternalToast) => string | number) & {
	success: (message: titleT | React$1.ReactNode, data?: ExternalToast) => string | number;
	info: (message: titleT | React$1.ReactNode, data?: ExternalToast) => string | number;
	warning: (message: titleT | React$1.ReactNode, data?: ExternalToast) => string | number;
	error: (message: titleT | React$1.ReactNode, data?: ExternalToast) => string | number;
	custom: (jsx: (id: number | string) => React$1.ReactElement, data?: ExternalToast) => string | number;
	message: (message: titleT | React$1.ReactNode, data?: ExternalToast) => string | number;
	promise: <ToastData>(promise: PromiseT<ToastData>, data?: PromiseData<ToastData>) => (string & {
		unwrap: () => Promise<ToastData>;
	}) | (number & {
		unwrap: () => Promise<ToastData>;
	}) | {
		unwrap: () => Promise<ToastData>;
	};
	dismiss: (id?: number | string) => string | number;
	loading: (message: titleT | React$1.ReactNode, data?: ExternalToast) => string | number;
} & {
	getHistory: () => (ToastT | ToastToDismiss)[];
	getToasts: () => (ToastT | ToastToDismiss)[];
};
declare const USER_ROLE_TYPES: readonly [
	"USER",
	"ADMIN"
];
declare const ytypingGlobal: {
	readonly toast: typeof toast;
	readonly getSessionUser: () => (Omit<import("better-auth", { with: { "resolution-mode": "import" } }).StripEmptyObjects<{
		id: string;
		createdAt: Date;
		updatedAt: Date;
		email: string;
		emailVerified: boolean;
		name: string;
		image?: string | null | undefined;
	} & {
		role: string;
		banned: boolean;
		warningCount: number;
	} & {
		banReason?: string | null | undefined;
	}>, "id" | "email"> & {
		id: number;
		role: (typeof USER_ROLE_TYPES)[number];
	}) | null;
	readonly setTypingLinkMode: (mode: "type" | "ime") => void;
};
declare global {
	interface Window {
		__ytyping: typeof ytypingGlobal;
	}
}
export type YTypingGlobal = typeof ytypingGlobal;
declare global {
	interface Window {
		__ytyping_type: YTypingTypeAPI;
		__ytyping_ime: YTypingImeAPI;
		__ytyping: YTypingGlobal;
	}
}

export {};
